name: masrofy
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  lottie: ^3.1.2
  smooth_page_indicator: ^1.2.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  provider: ^6.1.5+1
  fl_chart: ^0.69.0
  google_sign_in: ^6.1.5
  intl: ^0.20.2
  flutter_localizations:
    sdk: flutter

  font_awesome_flutter: ^10.7.0
  dash_chat_3: ^1.0.1
  
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/animations/logo.json
    - assets/animations/logo2.json
    - assets/animations/budget.json
    - assets/animations/spending.json
    - assets/animations/save.json
    - assets/animations/save1.json
    - assets/animations/success.json
    - assets/images/

l10n:
  arb-dir: l10n
  template-arb-file: app_en.arb
  output-localization-file: app_localizations.dart

  fonts:
    - family: WinkyRough
      fonts:
        - asset: assets/fonts/WinkyRough-VariableFont_wght.ttf
          weight: 400     