// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVeh6lGBJ0kRKr6SRhyHUB_ycK9V3aOLU',
    appId: '1:417652446499:web:7f9a163abbe16ea932e896',
    messagingSenderId: '417652446499',
    projectId: 'masrofy',
    authDomain: 'masrofy.firebaseapp.com',
    storageBucket: 'masrofy.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3Hv6JbI8s7vq1h6GacG4ecz2j5eM0Gkk',
    appId: '1:417652446499:android:d86b58f74590168232e896',
    messagingSenderId: '417652446499',
    projectId: 'masrofy',
    storageBucket: 'masrofy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB8ulH_1Pmshpj3UyTH9FcBZzzMgYfIcGw',
    appId: '1:417652446499:ios:7c045dba467231d532e896',
    messagingSenderId: '417652446499',
    projectId: 'masrofy',
    storageBucket: 'masrofy.firebasestorage.app',
    iosBundleId: 'com.example.masrofy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB8ulH_1Pmshpj3UyTH9FcBZzzMgYfIcGw',
    appId: '1:417652446499:ios:7c045dba467231d532e896',
    messagingSenderId: '417652446499',
    projectId: 'masrofy',
    storageBucket: 'masrofy.firebasestorage.app',
    iosBundleId: 'com.example.masrofy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVeh6lGBJ0kRKr6SRhyHUB_ycK9V3aOLU',
    appId: '1:417652446499:web:e4588d267a6d4ffe32e896',
    messagingSenderId: '417652446499',
    projectId: 'masrofy',
    authDomain: 'masrofy.firebaseapp.com',
    storageBucket: 'masrofy.firebasestorage.app',
  );

}